### PR TITLE
Bump versions and make default option mode to Root

### PR DESCRIPTION
**Pull request by enfipy**
First, it bumps Cargo versions. Second, it makes OptionMode default to Root to fix this kind of stuff:
```rs
#[serde(
    rename = "UIRequiresFullScreen",
    skip_serializing_if = "Option::is_none"
)]
requires_full_screen: Option<bool>
```
Results in:
```xml
<key>UIRequiresFullScreen</key>
<dict>
    <key>Some</key>
    <false />
</dict>
```

I haven't found how to work-around it and made changes to rust-plist. Also, I used rust-plist for our `Info.plist` [implementation](https://github.com/creator-rs/creator/tree/master/crates/creator-build/src/types/info_plist).

### CODE REVIEW

**Comment by ebarnard** [comment]
This PR seems to be failing a lot of tests.

**Comment by ebarnard** [comment]
In version 1.0 and above
```
struct Foo
    #[serde(rename = "UIRequiresFullScreen")]
    requires_full_screen: Option<bool>
}
```
with
```
let a = Foo { requires_full_screen: None }
```
should serialise to just
```
<plist></plist>
```

Can you give me a minimal complete example that does not work?

**Comment by enfipy** [comment]
In version 1.0.1:
```rs
struct Foo {
    #[serde(rename = "UIRequiresFullScreen")]
    requires_full_screen: Option<bool>
}
```

With `let a = Foo { requires_full_screen: Some(false) }`
Results in:
```
<plist>
<key> UIRequiresFullScreen</key>
<dict>
    <key>Some</key>
    <false />
</dict>
</plist>
```

**Comment by enfipy** [comment]
Sorry for failing tests, I broke something with the change of OptionMode.

**Comment by enfipy** [comment]
Also, I faced a similar weird behavior when I put an enum or vector of enums in a struct. So I had to add `skip_serializing_if = "Option::is_none"` and this as work-around:
```rs
fn serialize_enum_option<S: Serializer, T: Serialize>(
    value: &Option<T>,
    s: S,
) -> Result<S::Ok, S::Error> {
    s.serialize_str(&serde_plain::to_string(value).unwrap())
}

fn serialize_vec_enum_option<S: Serializer, T: Serialize>(
    value: &Option<Vec<T>>,
    s: S,
) -> Result<S::Ok, S::Error> {
    match value {
        Some(ref val) => {
            let mut seq = s.serialize_seq(Some(val.len()))?;
            for element in val.iter() {
                seq.serialize_element(&serde_plain::to_string(element).unwrap())?;
            }
            seq.end()
        }
        None => panic!("unsupported"),
    }
}

// serialize_with = "serialize_enum_option"
// serialize_with = "serialize_vec_enum_option"
```

**Comment by ebarnard** [comment]
> In version 1.0.1:
> 
> ```
> struct Foo {
>     #[serde(rename = "UIRequiresFullScreen")]
>     requires_full_screen: Option<bool>
> }
> ```
> ...

I've just tried this on master and I'm getting:

```rust
Event::StartDictionary(None),
Event::String("UIRequiresFullScreen".into()),
Event::Boolean(false),
Event::EndCollection,
```

using this test:

```rust
#[test]
fn pr_55() {
    #[derive(Debug, Deserialize, Eq, PartialEq, Serialize)]
    struct Foo {
        #[serde(rename = "UIRequiresFullScreen")]
        requires_full_screen: Option<bool>,
    }

    let expected = &[Event::StartDictionary(None), Event::EndCollection];
    let obj = Foo {
        requires_full_screen: None,
    };
    assert_roundtrip(obj, Some(expected));

    let expected = &[
        Event::StartDictionary(None),
        Event::String("UIRequiresFullScreen".into()),
        Event::Boolean(false),
        Event::EndCollection,
    ];
    let obj = Foo {
        requires_full_screen: Some(false),
    };
    assert_roundtrip(obj, Some(expected));
}
```

Are you *sure* you're on 1.0?

**Comment by enfipy** [comment]
@ebarnard Hmmm, it looks like it appears only with a wrapper struct that flattens the inner one. The version of plist is `1.0.0`.

I used it with flatten macro from the beginning so assumed that it will be broken in a simple example too.

Screen Shot 2020-12-23 at 11 58 23 PM

**Comment by ebarnard** [comment]
It looks like serde is serialising a flattened struct differently to if the fields just existed in the parent struct and `plist` thinks you're serialising a map (e.g. a `HashMap`). Hopefully, it's possible to detect flattening and match the behavior of a non-flattened struct.

The reason we have to treat maps specially is that `{ "foo": None }` must serialise to something different to `{}` so round-tripping `{ "foo": None }` ends up as `{ "foo": None }` and not `{}`.

**Comment by enfipy** [comment]
Yeah, you are right. Also, I noticed that if I round trip serialize and deserialize nested optional structs - it produces Some(<default velue>) instead of None.

And the last thing is that it was pretty tricky to serialize enums to string (as I specified earlier). Is this a correct behavior and I should keep it as I wrote?

**Comment by ebarnard** [comment]
The enum thing has been mentioned before - https://github.com/ebarnard/rust-plist/issues/53 - it should be possibly to change the behavior for fieldless enum variants to just serialise the string. I'd prefer to do that only for enums where all variants are fieldless, but I don't think serde exposes that information.

**Comment by ebarnard** [comment]
Unfortunately, it looks like serde serialises structs containing `#[flatten]` as maps rather than structs.:

```rust
use serde::Serialize;

#[derive(Serialize)]
struct Foo {
    a: Option<bool>,
    #[serde(flatten)]
    b: Bar,
}

#[derive(Serialize)]
struct Bar {
    c: Option<String>,
}
```

```rust
#[automatically_derived]
impl _serde::Serialize for Foo {
    fn serialize<__S>(&self, __serializer: __S)
     -> _serde::export::Result<__S::Ok, __S::Error> where
     __S: _serde::Serializer {
        let mut __serde_state =
            match _serde::Serializer::serialize_map(__serializer,
                                                    _serde::export::None)
                {
                _serde::export::Ok(__val) => __val,
                _serde::export::Err(__err) => {
                    return _serde::export::Err(__err);
                }
            };
        match _serde::ser::SerializeMap::serialize_entry(&mut __serde_state,
                                                         "a", &self.a)
            {
            _serde::export::Ok(__val) => __val,
            _serde::export::Err(__err) => {
                return _serde::export::Err(__err);
            }
        };
        match _serde::Serialize::serialize(&&self.b,
                                           _serde::private::ser::FlatMapSerializer(&mut __serde_state))
            {
            _serde::export::Ok(__val) => __val,
            _serde::export::Err(__err) => {
                return _serde::export::Err(__err);
            }
        };
        _serde::ser::SerializeMap::end(__serde_state)
    }
}
```
as such, I'm not sure there's anything we can do to support skipping `None` fields in `#[flatten]` containing structs.

Moreover as this is supported a supported use of `#[flatten]`:
```rust
#[derive(Serialize, Deserialize)]
struct User {
    id: String,
    username: String,

    #[serde(flatten)]
    extra: HashMap<String, Value>,
}
```
I don't think it is possible to fix this in `serde` without changing existing semantics. The only option would be to introduce something like `#[flatten_struct]` or `#[flatten(struct)]`.

**Comment by ebarnard** [comment]
There seem to be quite a few idiosyncrasies with `#[flatten]`: https://github.com/serde-rs/serde/issues?q=is%3Aissue+is%3Aopen+flatten

**Comment by enfipy** [comment]
That's sad! Is it also not possible to always ignore `Option` with some special `serialize_with` function?

**Comment by ebarnard** [comment]
I’m not sure how that could combine with flatten as the serialize_with would have to be on the outer struct rather than just on the Option.

**Comment by ebarnard** [comment]
Maybe a combination of  `skip_serializing_if = "Option::is_none"` and `serialise_with = "XXX"` where `XXX` just serialises the contents of the `Option` would work.

Not sure how that would interact with the current deserialiser but it should serialise correctly.

**Comment by ebarnard** [comment]
As an aside, serialising a plain enum e.g.
```rust
enum Foo {
    A,
    B,
    C
}
```
should serialise directly to a string as of plist 1.1

**Comment by enfipy** [comment]
@ebarnard That's cool news about enum, thanks!

Also, is it possible to make the `XXX` function publically available from rust-plist for such cases?

**Comment by ebarnard** [comment]
The solution ends up being a bit, but not too much, more involved. I'm not going to add `deserialize_some` and `serialize_some` as public functions in `plist`, but an example in the docs would be good.

```rust
#[test]
fn flattened_optional_fields() {
    fn deserialize_some<'de, D, T>(de: D) -> Result<Option<T>, D::Error>
    where
        D: de::Deserializer<'de>,
        T: Deserialize<'de>,
    {
        T::deserialize(de).map(Some)
    }

    fn serialize_some<S, T>(value: &Option<T>, ser: S) -> Result<S::Ok, S::Error>
    where
        S: ser::Serializer,
        T: Serialize,
    {
        value
            .as_ref()
            .expect(
                r#"`serialize_some` must be used with `skip_serializing_if = "Option::is_none"`"#,
            )
            .serialize(ser)
    }

    #[derive(Debug, Deserialize, PartialEq, Serialize)]
    struct Foo {
        #[serde(
            default,
            deserialize_with = "deserialize_some",
            serialize_with = "serialize_some",
            skip_serializing_if = "Option::is_none"
        )]
        a: Option<bool>,
        #[serde(
            default,
            deserialize_with = "deserialize_some",
            serialize_with = "serialize_some",
            skip_serializing_if = "Option::is_none"
        )]
        b: Option<i32>,
        #[serde(flatten)]
        flattened: Bar,
    }

    #[derive(Debug, Deserialize, PartialEq, Serialize)]
    struct Bar {
        #[serde(
            default,
            deserialize_with = "deserialize_some",
            serialize_with = "serialize_some",
            skip_serializing_if = "Option::is_none"
        )]
        c: Option<String>,
        #[serde(
            default,
            deserialize_with = "deserialize_some",
            serialize_with = "serialize_some",
            skip_serializing_if = "Option::is_none"
        )]
        d: Option<f64>,
    }

    let expected = &[
        Event::StartDictionary(None),
        Event::String("b".into()),
        Event::Integer((-12).into()),
        Event::String("d".into()),
        Event::Real(2.4),
        Event::EndCollection,
    ];
    let obj = Foo {
        a: None,
        b: Some(-12),
        flattened: Bar {
            c: None,
            d: Some(2.4),
        },
    };
    assert_roundtrip(obj, Some(expected));
}
```

**Pull request closed without merging**
