### PR TITLE
Add support for UID and a Deserializer::from_reader function

### PR DESCRIPTION
**Pull request by spease**

### CODE REVIEW

**Comment by ebarnard** [comment]
I'm happy to add support for UIDs but the issue with supporting UIDs in this way is a data structure with a field that that deserialises from a UidValue will serialise to an IntegerValue.

To support round trip serialisation I used a hack from the `toml` crate. You can see it in action in https://github.com/ebarnard/rust-plist/blob/master/src/date.rs.

UIDs will need a newtype similar to
```rust
pub struct Uid(pub u64)
```
and a `Serialize`/`Deserialize` impl similar to `Date`.

**Comment by spease** [comment]
You mean if you transcode from binary to XML? The way I did it, somebody can still use a newtype exactly like you specified as long as they #[derive(Deserialize)], unless you're handling newtypes differently than the serde recommendation to treat them as nonexistent wrappers. Alternatively, if you transcode to something like JSON or specify a u64 type in a struct definition, they automatically become integers (I'm not sure what else they could be).

**Comment by spease** [comment]
I took another closer look at Date, and I think I may be missing a key piece of knowledge. I've never used the `serializer.serialize_newtype_struct(DATE_NEWTYPE_STRUCT_NAME, &date_str)` function before, and I don't understand why the name is being passed.

But then when I look at the events, it looks like it gets turned into a string and treated as a string value.

So right now I'm not really sure I understand the rationale here, since it looks like this isn't very efficient or more type-safe. It seems with Date you could potentially deserialize to a String type, just like you could deserialize a UID to a u64, the only difference is that the intermediate transport from the encoding-specific reader to the serde deserializer is different.

Ahh - I think I see it. There's then no way _at all_ to serialize to a UID type since there's no way to trigger the UID events from serialization? I hadn't thought of that since I was exclusively focused on serialization.

**Comment by ebarnard** [comment]
Yes, it's partly that you can't serialise it.

It's also that having a UID deserialise to a u64 makes serialisation and deserialisation harder to reason about as the types values in a plist are not preserved through a deserialisation and serialisation cycle. i.e.

**Deserialisation**
`IntegerValue`, `UidValue` -> `u64`
`IntegerValue` -> `i64`, `usize`, `isize`, `u32`, `i32`, `u16`, `i16`, `u8`, `i8`

**Serialisation**
 `u64`, `i64`, `usize`, `isize`, `u32`, `i32`, `u16`, `i16`, `u8`, `i8` -> `IntegerValue`

So your input Plist starts with some UID values and ends up containing only integers.

It's the same reason a `DateValue` **can't** be deserialised to just a `String`.

**Comment by spease** [comment]
@ebarnard It's been awhile since I submitted this and I'm not sure if/when I'm going to be able to fix it...please consider this orphaned at this point. :(

**Comment by ebarnard** [comment]
Ok. Thanks for letting me know.

**Pull request closed without merging**
