### PR TITLE
Emit doctype, better match Apple's plist output

### LINKED ISSUE #26: XML output does not include DOCTYPE
A proper plist includes a DOCTYPE

```xml
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
```

The output from this crates does not include this doctype.

Also, less importantly, the output from Apple's plist code capitalizes the encoding name, i.e.

```xml
<?xml version="1.0" encoding="UTF-8"?>
```

but the output from this crate lowercases it.

### PR DESCRIPTION
**Pull request by kballard**
Change the plist output to match Apple's. This means uppercasing the XML encoding, including a doctype, indenting using hard tabs, and stripping one level of indentation from the file.

The implementation here isn't great, because xml-rs doesn't have any way of emitting a doctype directly (see netvl/xml-rs#168), but it works.

Fixes #26.

### CODE REVIEW

**Comment by ebarnard** [comment]
I've got no objections to fixing #26 and it would be good to have the output match Apple's native plist writer. But as this is hopefully a temporary fix I'd like it to be as minimal as possible.

I think it we set `EmitterConfig::perform_escaping(false)` and change `EventWriter::write_value` to call `xml::escape::escape_str_pcdata` on the text to be written we could just write an `XmlEvent::Characters` containing the DTD, XML header before the opening plist tag.

**Comment by kballard** [comment]
Good idea. Not sure why that didn't occur to me. I'll try it out when I get a chance (hopefully tonight, but no promises).

**Comment by kballard** [comment]
@ebarnard I've updated the PR to use the approach you suggested.

**Comment by ebarnard** [comment]
Thanks!

**Pull request merged**
