### PR TITLE
Update base64

### PR DESCRIPTION
**Pull request by kornelski**

### CODE REVIEW

**Comment by ebarnard** [comment]
This bumps the minimum Rust version which I want to restrict to minor version releases. So this will have to wait until 0.6.

**Comment by nox** [comment]
@ebarnard Do you have any ETA for 0.6?

**Comment by ebarnard** [comment]
Not particularly. I'm happy enough with the API that it's probably time to do a 1.0 release anyway.

**Comment by nox** [comment]
Any ETA for 1.0 then? I am trying to reduce the number of different versions of base64 in my crate graph.

**Comment by ebarnard** [comment]
Really just want to get #49 sorted out, I'm just hoping to find something with fewer dependencies than chrono.

**Comment by ebarnard** [comment]
Merged in f27f779f153f2faca2a850eda660602968d31ade and released in 1.0.

**Pull request closed without merging**
