### PR TITLE
Add .pad_self_closing(false) to improve compatibility with Apple's XML parser

### PR DESCRIPTION
**Pull request by kristopherjohnson**
Adds `.pad_self_closing(false)` to the initialization of the `EmitterConfig` used by `stream::XmlWriter`.

This change causes self-closing tags to be generated as, for example, `<true/>` rather than `<true />`. Apple XML parser used by the `codesign` utility does not accept the later as valid.

See #65 for discussion.

### CODE REVIEW

**Comment by ebarnard** [comment]
Looks like a dependency update has bumped the MSRV again.

**Comment by ebarnard** [comment]
Try rebasing atop master now

**Comment by kristopherjohnson** [comment]
Done.

**Comment by ebarnard** [comment]
Thanks, merged via 1a9bf1e9.

**Comment by ebarnard** [comment]
Released in 1.2.0.

**Pull request closed without merging**
