### PR TITLE
Added support for key tag

### PR DESCRIPTION
**Pull request by literator**
I'd like to propose `key ` tag support. Most plist files, at least those used by Apple, use `key` tag instead of simple `string` extensively. When you're working with e.g. iOS plists this feature is a must have.

What do you think?

### CODE REVIEW

**Comment by ebarnard** [comment]
Hi. Initially there was a DictionaryKey variant that did exactly what you propose. Unfortunately apple's binary plist format allows you to use dictionary keys other than strings so I changed the format for dictionaries to alternate keys and values:

```
StartDictionary
StringValue("Name") // This is the key
StringValue("James") // This is the value
StringValue("Age") // Key
IntValue(42) // Value
EndDictionary
```

If all you want to read a plist file I would recommend using a `Builder` to create a [`Plist`](https://ebarnard.github.io/rust-plist/plist/enum.Plist.html) object. Unfortunately non of this is yet documented anywhere.

**Comment by literator** [comment]
I understand your point. Reading is not a problem. 
Unfortunately I have to write plist and I need valid format with keys.
Maybe it would be better if there is an option to use string or key value when writing.

**Comment by ebarnard** [comment]
Ah. The xml writer's currently broken, it would need some internal state to keep track of whether it's writing a key or value. I still haven't found any examples of plists in the wild with non primitive keys so I'm tempted to just create StringKey, IntKey etc.

**Comment by literator** [comment]
I see. To honest I don't recall any example with non string key even.
Anyways, looking forward to it.
Closing the PR.

Thanks!

**Comment by ebarnard** [comment]
@literator 
Tbh I haven't seen it on a normal plist. Just when used for serialisation - which isn't a use case I want to support.

Anyway the xml writer should be working now using the original key value scheme e.g.
```
StringValue("Name") // This is the key
StringValue("James") // This is the value
```

**Comment by literator** [comment]
Awesome! Thanks!

**Pull request closed without merging**
