### PR TITLE
Add Dictionary.retain

### PR DESCRIPTION
**Pull request by madig**
I just happen to need this in a project because I don't know how else to do it :)

### CODE REVIEW

**Comment by madig** [comment]
Not sure what's going on in that one CI job...

**Comment by ebarnard** [comment]
Me neither, looks unrelated to this PR though. Need to migrate to GitHub actions soon anyway.

**Comment by ebarnard** [comment]
Released in v1.0.1.

**Comment by madig** [comment]
Thanks!

**Pull request merged**
