### PR TITLE
WIP: Use quick-xml instead of xml-rs

### PR DESCRIPTION
**Pull request by pr2502**
Hi! This is a very quick-and-dirty experiment to see if the perf gains are worth it, if you'd be interested in this at all I'll gladly clean it up to what you think is a mergeable state.

I've tried using rust-plist for parsing void-linux package repositories which are about 15MB of xml-encoded plist, with the latest release from crates.io parsing that took roughly 2.4s, with this patch to rust-plist it only took 0.23s which is much closer to what xbps-query (the void-linux cli tool which queries the repository) takes (xbps takes about 0.3s but i think it's doing extra work, i didn't try to isolate the parsing).

### CODE REVIEW

**Comment by ebarnard** [comment]
I'd be happy to switch to quick-xml. From what you say it looks like there are performance improvements to be had.

I'd prefer to completely replace xml-rs, instead of adding quick-xml as a separate feature.

**Comment by ebarnard** [comment]
No worries about the delay.

IMO, the best way to solve the tag closing problem would be to defer writing collection openers until the next event is emitted. You could store an `Option<PendingCollection>` in the `XmlWriter` where:
```rust
enum PendingCollection {
    Array,
    Dictionary
}
```
which is set to `Some(...)` whenever a collection start event is received and writing is deferred until the next event is received. Should be relatively straightforward.

**Comment by wyatt-herkamp** [comment]
xml-rs is no longer maintained. So @pr2502 could you use some help with this update?

**Comment by ebarnard** [comment]
Superseded by #88.

**Pull request closed without merging**
