### PR TITLE
Implement methods that allow access to the Plist values.

### PR DESCRIPTION
**Pull request by zummenix**
This is basically the same as in `serde_json`.

### CODE REVIEW

**Comment by zummenix** [comment]
The build error seems unrelated. @ebarnard, do you want me to fix it in this PR?

**Comment by ebarnard** [comment]
Don't worry about the build error.

PR's good except can you drop as_data_mut and change as_data to return &[u8]. It seems odd to give mutable access to Data but not to String.

**Comment by zummenix** [comment]
Sure. Done.

**Comment by ebarnard** [comment]
Thanks

**Pull request merged**
